# .github/workflows/main.yml
name: Python Test and Webhook

on:
  push:
    branches: [ main, master ] # Adjust to your default branch
  pull_request:
    branches: [ main, master ] # Adjust to your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  test_and_report:
    runs-on: ubuntu-latest
    # The job status will be 'success' or 'failure' based on the test step.
    # If tests fail, the job fails, and job.status will reflect that.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Run unit tests
        id: run_tests
        run: |
          python -m unittest test.py

      - name: Send to Webhook
        # This step will run even if previous steps fail.
        # `job.status` will correctly reflect 'failure' if the tests failed.
        if: always()
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          JSON_PAYLOAD=$(cat <<EOF
          {
            "repository": "${{ github.repository }}",
            "commit_sha": "${{ github.sha }}",
            "run_id": ${{ github.run_id }},
            "run_number": ${{ github.run_number }},
            "workflow_name": "${{ github.workflow }}",
            "event_name": "${{ github.event_name }}",
            "branch_ref": "${{ github.ref }}",
            "actor": "${{ github.actor }}",
            "job_status": "${{ job.status }}",
            "timestamp": "$TIMESTAMP",
            "report_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
          EOF
          )
          echo "Sending JSON Payload:"
          echo "$JSON_PAYLOAD"

          if [ -z "${{ secrets.WEBHOOK_URL }}" ]; then
            echo "secrets.WEBHOOK_URL not defined, finishing"
          else
            curl -X POST \
                    -H "Content-Type: application/json" \
                    -H "X-Github-Event: ${{ github.event_name }}" \
                    -d "$JSON_PAYLOAD" \
                    "${{ secrets.WEBHOOK_URL }}"
          fi
